DECLARE @ESTADIOS_HOME TABLE (ESTADIO VARCHAR(300))
insert @ESTADIOS_HOME (ESTADIO) values ('BEIRA-RIO')
insert @ESTADIOS_HOME (ESTADIO) values ('EUCALIPTOS')
insert @ESTADIOS_HOME (ESTADIO) values ('CHÁCARA DOS EUCALIPTOS')
insert @ESTADIOS_HOME (ESTADIO) values ('INTERNACIONAL')
insert @ESTADIOS_HOME (ESTADIO) values (NULL)

/*OS GRENAIS SAO CARREGADOS DE OUTRA PLANILHA*/
delete from PERIN where Adversario = 'GRÊMIO'

UPDATE PERIN SET Adversario = 'Ec Bahia' WHERE Adversario = 'BAHIA'
UPDATE PERIN SET Adversario = 'RB Bragantino' WHERE Adversario = 'BRAGANTINO'
UPDATE PERIN SET Adversario = 'Coritiba FC' WHERE Adversario = 'CORITIBA'
UPDATE PERIN SET Adversario = 'Flamengo' WHERE Adversario = 'FLAMENGO '
UPDATE PERIN SET Adversario = 'São Paulo' WHERE Adversario = 'SÃO PAULO '

UPDATE PERIN SET Adversario = 'Atlético-PR' WHERE Adversario = 'ATLÉTICO PARANAENSE'
UPDATE PERIN SET Adversario = 'Goiás EC' WHERE Adversario = 'GOIÁS'
UPDATE PERIN SET Adversario = 'Santos FC' WHERE Adversario = 'SANTOS'

INSERT INTO game (idChampionship, idStadium, idTeamHome, scoreTeamHome, scoreTeamAway, idTeamAway, gameDate, source)
SELECT 
	CASE 
		WHEN CAMPEONATO = 'INTERNACIONAL AMISTOSO' THEN 'AMISTOSO'
		WHEN CAMPEONATO = 'AMISTOS' THEN 'AMISTOSO'
		WHEN CAMPEONATO = 'AMISTOSO' THEN 'AMISTOSO'
		WHEN CAMPEONATO = 'TORNEIO INTERNACIONAL' THEN 'INDEFINIDO'
		WHEN CAMPEONATO = 'TORNEIO' THEN 'INDEFINIDO'
		WHEN CAMPEONATO = 'SELETIVA LIBERTADORES' THEN CAST(YEAR(data) AS VARCHAR(4))+'_SLA'
		WHEN CAMPEONATO = 'GAÚCHO' THEN CAST(YEAR(data) AS VARCHAR(4))+'_RS'
		WHEN CAMPEONATO = 'CITADINO' THEN CAST(YEAR(data) AS VARCHAR(4))+'_CIT'
		WHEN CAMPEONATO = 'COPA DO BRASIL' THEN CAST(YEAR(data) AS VARCHAR(4))+'_CDB'
		WHEN CAMPEONATO = 'LIBERTADORES' THEN CAST(YEAR(data) AS VARCHAR(4))+'_LA'
		WHEN CAMPEONATO = 'BRASILEIRO' THEN CAST(YEAR(data) AS VARCHAR(4))+'_BR'
		WHEN CAMPEONATO = 'ROBERTÃO' THEN CAST(YEAR(data) AS VARCHAR(4))+'_RGP'
		WHEN CAMPEONATO = 'TAÇA DE PRATA' THEN CAST(YEAR(data) AS VARCHAR(4))+'_RGP'		
		WHEN CAMPEONATO = 'MERCOSUL' THEN CAST(YEAR(data) AS VARCHAR(4))+'_MER'
		WHEN CAMPEONATO = 'COPA SUL' THEN CAST(YEAR(data) AS VARCHAR(4))+'_CSUL'
		WHEN CAMPEONATO = 'TAÇA BRASIL' THEN CAST(YEAR(data) AS VARCHAR(4))+'_TBR'
		WHEN CAMPEONATO = 'COPA SUL-MINAS' THEN CAST(YEAR(data) AS VARCHAR(4))+'_CSM'
	END idChampionship,
	CASE
		WHEN PERIN.Estadio = 'NULL' THEN NULL
		ELSE (SELECT MAX(ID) FROM stadium WHERE UPPER(NAME) LIKE UPPER(TRIM(PERIN.Estadio)) or UPPER(nickname) LIKE UPPER(TRIM(PERIN.Estadio)))
	END idStadium, 
	CASE
		WHEN H.ESTADIO IS NOT NULL THEN 1
		ELSE (SELECT MAX(ID) FROM team WHERE UPPER(NAME) LIKE UPPER(Adversario))
	END idTeamHome,
	CASE
		WHEN H.ESTADIO IS NOT NULL THEN Gols_Pro
		ELSE Gols_Contra
	END scoreTeamHome,
	CASE
		WHEN H.ESTADIO IS NOT NULL THEN Gols_Contra
		ELSE Gols_Pro
	END scoreTeamAway,
	CASE
		WHEN H.ESTADIO IS NULL THEN 1 
		ELSE (SELECT MAX(ID) FROM team WHERE UPPER(NAME) LIKE UPPER(Adversario))
	END idTeamAway,
	Data gameDate,
	'Perin' source
	--, PERIN.Estadio, Adversario, CAMPEONATO
  FROM PERIN 
	LEFT JOIN @ESTADIOS_HOME H ON PERIN.Estadio = H.ESTADIO